---

- name: "add node LTS version and NVM , then using node 13.8.0 version"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install -g n
    sudo n 13.8.0
- name: "install pm2"
  npm:
    name: pm2
    global: yes











# - name: install nvm 
#   shell: |
#       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
# - name: install node 13.8 
#   shell: |
#       export NVM_DIR="$HOME/.nvm"
#       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#       [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#       nvm install 13.8


# - name: install global packages
#   apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
#   become: True
#   become_method: sudo
#   with_items:
#     - python3
#     - npm 













# - name: "add Node.js 13"
#   become: true
#   shell: |
#     # Install Node.js LTS version as our base Node.js version
#     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

# - name: "Install Node.js 13"
#   become: true
#   apt:
#     name: [ "nodejs"]
#     state: latest
#     update_cache: yes
  
#     # Use n version manager to switch to Node.js v13.8.0

# - name: "Install PM2 Globally"
#   npm:
#     name: pm2
#     global: yes   


# - name: "add Node.js 13"
#   become: true
#   shell: |
#     # Install Node.js LTS version as our base Node.js version
#     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

# - name: "Install Node.js 13"
#   become: true
#   apt:
#     name: [ "nodejs"]
#     state: latest
#     update_cache: yes
  
#     # Use n version manager to switch to Node.js v13.8.0

# - name: "Install PM2 Globally"
#   npm:
#     name: pm2
#     global: yes    


 